### ISSUE TITLE
Stake display after unstaking with P7

### ISSUE THREAD

**Issue by chportma** [Concordium/concordium-scan#265]
**Bug Description**

CCD scan displays incorrectly the stake after P7 and produces a wrong information message when stake is in cool-down. It seems to display stake = active + inactive stake, instead of just active stake. The message says that "Stake will be reduced to Ͼ XXX in YYY days", when the stake has already been reduced and will be unlocked in YYY days. See screenshot attached.

**Steps to Reproduce**

Unstake some CCD, wait for the next pay day.

**Expected Result**

The new stake should be displayed after the pay day, because a stake change is immediately effective (well, at the next pay day), i.e., stake displayed = active stake.

There should probably also be a new line for the total stake in cool-down, i.e., inactive stake.

It is unclear what the expected message should be. Since there can be a queue of inactive stake to be unlocked on different days, this is inconvenient to display. Maybe the message should be removed altogether, until we can properly revise CCD scan.

**Actual Result**

The stake displayed = active + inactive stake, i.e., effective stake + CCD in cool-down.

There is no mention of how much stake is in cool-down.

**Versions**

CCD scan version 1.5.41/1.8.19

<img width="506" alt="Screenshot 2024-10-03 at 17 06 33" src="https://github.com/user-attachments/assets/d246055a-1565-460b-9ca1-9b7306084390">

**Comment by LeoNore-ort** [comment]
@chportma Thanks for posting the issue.

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://allchainrectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by limemloh** [comment]
This is fixed in #214 and released in CCDscan backend 1.9.1.
Unfortunately, the testnet release got delayed, but will be out soon

**Comment by limemloh** [comment]
The fix is now out on Testnet as well

**Comment by chportma** [comment]
@limemloh , I have just checked this again in more detail, and the stake displayed on CCDscan still doesn't look right. For my testnet account `3MdqExQigqLr8NkEABerEJ2B7Ujao5mqHH7hYh2n2bKYdXg4tR`, my last delegation transaction was:
`Delegator 3MdqEx (id 11459) increased stake to 13,006.914311Ͼ`
That was 5 days ago. So with the reward restaking, I should have around 13'030 CCD staked. But CCDscan displays 
`7,006.430314 Staked`
I hope that this is a bug in CCDScan and not in the core protocol.
<img width="883" alt="Screenshot 2024-10-08 at 11 55 30" src="https://github.com/user-attachments/assets/9ea1f730-fecb-4070-9fbb-fb7d82ccfa5a">
<img width="883" alt="Screenshot 2024-10-08 at 11 55 55" src="https://github.com/user-attachments/assets/e0a8d23c-aa8f-4d48-9b69-bbd6ad1e3639">

**Comment by limemloh** [comment]
Checking the account using concordium-client seems to indicate it is a CCDscan issue:

```
concordium-client --grpc-ip grpc.testnet.concordium.com --grpc-port 20000 --secure account show 3MdqExQigqLr8NkEABerEJ2B7Ujao5mqHH7hYh2n2bKYdXg4tR               
Local names:            
Address:                3MdqExQigqLr8NkEABerEJ2B7Ujao5mqHH7hYh2n2bKYdXg4tR
Balance:                20022.825261 CCD
 - At disposal:          4993.171903 CCD
Nonce:                  16
Encryption public key:  b14cbfe44a02c6b1f78711176d5f437295367aa4f2a8c2551ee10d25a03adc69d61a332a058971919dad7312e1fc94c5b19d878c5eac3b5e8efeed963d01ff08f70d494cc8d0d17d43de89e1f663d83332a690d13a423fc3ff7ad3e35ef71847

Delegating stake: yes
Delegation target: Passive delegation
 - Staked amount: 13029.653358 CCD
 - Restake earnings: yes
Inactive stake in cooldown:
   1000.000000 CCD available after Wed,  9 Oct 2024 12:00:24 UTC
   1000.000000 CCD available after Thu, 10 Oct 2024 12:00:24 UTC
```

<br>This is most likely data corruption due to the delayed release on testnet, we are reindexing the chain, but it will probably take another week before the fix is out.

**Comment by chportma** [comment]
Thanks for the clarification. I will close the issue again, and double check when the fix is out.
